{
  inputs,
  lib,
  flake-parts-lib,
  config,
  ...
}:
let
  outerCfg = config.files;
in
{
  imports = [ inputs.files.flakeModules.default ];

  options = {
    files.generatedMessage = {
      text = lib.mkOption {
        type = lib.types.str;
        description = "Text to include in the generated comment at the top of generated files.";
        default = "This file is @generated by `nix run .#generate-files`, do not edit directly.";
      };
      commentFormatters = lib.mkOption {
        type = lib.types.attrsOf (lib.types.functionTo lib.types.str);
        description = "Functions to format comments for different file types.";
        default =
          let
            hashtag = text: "# ${text}";
          in
          {
            md = text: "<!-- ${text} -->";
            sh = hashtag;
            envrc = hashtag;
            gitignore = hashtag;
            toml = hashtag;
            license = _: "";
          };
        readOnly = true;
      };
    };

    perSystem = flake-parts-lib.mkPerSystemOption (
      { config, pkgs, ... }:
      let
        cfg = config.files;
      in
      {
        options.files = {
          file = lib.mkOption {
            type = lib.types.attrsOf (
              lib.types.submodule (
                {
                  name,
                  config,
                  ...
                }:
                {
                  options = {
                    fileType = lib.mkOption {
                      type = lib.types.enum (lib.attrNames outerCfg.generatedMessage.commentFormatters);
                      description = "Type of the file, used to determine comment style.";
                      default = lib.toLower (lib.last (lib.splitString "." name));
                    };
                    text = lib.mkOption {
                      type = lib.types.nullOr lib.types.lines;
                      description = "Text content of the file.";
                      default = null;
                    };
                    source = lib.mkOption {
                      type = lib.types.path;
                      description = "Path to a source file to use as the content of the file.";
                    };
                  };

                  config = {
                    source = lib.mkIf (config.text != null) (pkgs.writeText "file-${name}" config.text);
                  };
                }
              )
            );
          };
        };

        config = {
          files.files = lib.mapAttrsToList (
            name:
            { fileType, source, ... }:
            {
              path_ = name;
              drv =
                pkgs.runCommandLocal "files-${name}"
                  {
                    comment =
                      let
                        mkComment = outerCfg.generatedMessage.commentFormatters.${fileType};
                      in
                      if mkComment != null then mkComment outerCfg.generatedMessage.text else "";
                    inherit source;
                  }
                  ''
                    touch $out
                    if [ -n "$comment" ]; then
                      echo "$comment" >> $out
                    fi
                    cat "${source}" >> $out
                  '';
            }
          ) cfg.file;
        };
      }
    );
  };

  config = {
    flake-file.inputs.files.url = "github:mightyiam/files";
  };
}
