version: 2
updates:
  - package-ecosystem: nix
    directory: /
    commit-message:
      prefix: chore(flake-inputs)
    schedule:
      interval: daily
    registries:
      github:
        type: git
        url: ssh://git@github.com
        username: x-access-token
        password: ${{ secrets.FONTS_PAT }}
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: chore(ci)
    schedule:
      interval: daily
