version: 2

updates:
  - package-ecosystem: nix
    directory: /
    commit-message:
      prefix: flake
    registries: "*"
    cooldown:
      exclude:
        - "*"
    open-pull-requests-limit: 64
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ci
    open-pull-requests-limit: 64
    schedule:
      interval: daily

registries:
  github:
    type: git
    url: ssh://git@github.com
    username: x-access-token
    password: ${{ secrets.FONTS_PAT }}
