use_global = false
exclude_tags = ["identifier"]
ignore_paths = [
  ".envrc",
  ".github/actions/**",
  ".github/dependabot.yaml",
  ".github/workflows/**",
  ".gitignore",
  ".harper-dictionary.txt",
  ".sops.yaml",
  "**/*.nix",
  "**/*.patch",
  "codebook.toml",
  "flake.lock",
  "modules/hosts/*/facter.json",
  "secrets.yaml",
]
words = [
  "bhatt",
  "bot's",
  "cachyos",
  "dependabot",
  "dependabot's",
  "direnv",
  "hyprcursor",
  "hyprcursors",
  "hyprland",
  "llm",
  "nixos",
  "nixpkgs",
  "noninfringement",
  "passthru",
  "steamrt",
  "steamrtarm",
  "stylix",
  "sublicense",
  "tailscale",
  "toplevel",
  "treefmt",
  "vidhan",
  "vidhanix",
  "waywall",
  "waywork",
]
