# This file is @generated by `just generate`, do not edit directly.
{
  outputs = inputs: inputs.flake-parts.lib.mkFlake { inherit inputs; } (inputs.import-tree ./modules);

  nixConfig = {
    allow-import-from-derivation = false;
    extra-experimental-features = [
      "nix-command"
      "flakes"
    ];
    extra-substituters = [
      "https://attic.xuyh0120.win/lantian"
      "https://cache.numtide.com"
      "https://nix-community.cachix.org"
    ];
    extra-trusted-public-keys = [
      "lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc="
      "niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
  };

  inputs = {
    agentcord.url = "github:vidhanio/agentcord";
    disko.url = "github:vidhanio/disko/feature/skip-partition-uuid";
    files = {
      url = "github:mightyiam/files";
      flake = false;
    };
    flake-aspects.url = "github:denful/flake-aspects";
    flake-file.url = "github:vidhanio/flake-file/fix/write-flake-mtime-churn";
    flake-parts = {
      url = "github:hercules-ci/flake-parts";
      inputs.nixpkgs-lib.follows = "nixpkgs";
    };
    git-hooks-nix.url = "github:cachix/git-hooks.nix";
    helium.url = "github:schembriaiden/helium-browser-nix-flake";
    home-manager.url = "github:nix-community/home-manager";
    impermanence.url = "github:nix-community/impermanence";
    import-tree.url = "github:vic/import-tree";
    llm-agents.url = "github:numtide/llm-agents.nix";
    mattpocock-skills = {
      url = "github:mattpocock/skills";
      flake = false;
    };
    mcsr = {
      url = "https://git.uku3lig.net/uku/mcsr-nixos/archive/main.tar.gz";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-auto-follow = {
      url = "github:vidhanio/nix-auto-follow/merge-fix-inputs-references";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-cachyos-kernel.url = "github:xddxdd/nix-cachyos-kernel/release";
    nix-index-database.url = "github:nix-community/nix-index-database";
    nixcord.url = "github:4evy/nixcord";
    nixos-apple-silicon.url = "github:nix-community/nixos-apple-silicon";
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    nixvim.url = "github:nix-community/nixvim";
    sops-nix.url = "github:Mic92/sops-nix";
    spicetify-nix.url = "github:Gerg-L/spicetify-nix";
    stylix.url = "github:nix-community/stylix";
    systems.url = "github:nix-systems/default-linux";
    tinted-schemes = {
      url = "github:tinted-theming/schemes";
      flake = false;
    };
    treefmt-nix.url = "github:numtide/treefmt-nix";
    vidhan-fonts = {
      url = "git+ssh://git@github.com/vidhanio/fonts";
      flake = false;
    };
  };
}
