# This file is @generated by `nix run .#generate-files`, do not edit directly.
{

  outputs = inputs: inputs.flake-parts.lib.mkFlake { inherit inputs; } (inputs.import-tree ./modules);

  nixConfig = {
    allow-import-from-derivation = false;
    extra-substituters = [
      "https://nixos-apple-silicon.cachix.org"
      "https://cache.numtide.com"
      "https://nix-community.cachix.org"
    ];
    extra-trusted-public-keys = [
      "nixos-apple-silicon.cachix.org-1:8psDu5SA5dAD7qA0zMy5UT292TxeEPzIz8VVEr2Js20="
      "niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
  };

  inputs = {
    agenix.url = "github:ryantm/agenix";
    disko.url = "github:nix-community/disko";
    files.url = "github:mightyiam/files";
    flake-file.url = "github:vic/flake-file";
    flake-parts = {
      inputs.nixpkgs-lib.follows = "nixpkgs-lib";
      url = "github:hercules-ci/flake-parts";
    };
    ghostty-shader-playground = {
      flake = false;
      url = "github:KroneCorylus/ghostty-shader-playground";
    };
    git-hooks-nix.url = "github:cachix/git-hooks.nix";
    home-manager.url = "github:nix-community/home-manager";
    impermanence.url = "github:nix-community/impermanence";
    import-tree.url = "github:vic/import-tree";
    llm-agents.url = "github:numtide/llm-agents.nix";
    nix-index-database.url = "github:nix-community/nix-index-database";
    nixcord.url = "github:FlameFlag/nixcord";
    nixos-apple-silicon.url = "github:nix-community/nixos-apple-silicon";
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    nixpkgs-lib.follows = "nixpkgs";
    nixvim.url = "github:nix-community/nixvim";
    spicetify-nix.url = "github:Gerg-L/spicetify-nix";
    stylix.url = "github:nix-community/stylix";
    systems.url = "github:nix-systems/default-linux";
    treefmt-nix.url = "github:numtide/treefmt-nix";
    vidhan-fonts = {
      flake = false;
      url = "git+ssh://git@github.com/vidhanio/fonts";
    };
    vscode-extensions.url = "github:nix-community/nix-vscode-extensions";
  };

}
