# This file is @generated by `just generate`, do not edit directly.
set no-cd

mod build
mod docs
mod eval
mod inspect

hmConfig := nixosConfig + ".home-manager.users." + user
host := `hostname`
nixosConfig := ".#nixosConfigurations." + host + ".config"
perSystemConfig := ".#allSystems." + system + ".config"
system := `nix eval --raw --impure --expr 'builtins.currentSystem'`
systemPackage := nixosConfig + ".system.build.toplevel"
user := `whoami`

# list the available recipes in all justfiles
@default:
    just --list --list-submodules

# record the intent to add each new file, so that the flake sees it
@add:
    git add -AN

# regenerate the generated files
@generate: add
    nix run .#generate-files

# regenerate the files, then run `nh os` with the given action
@os action="switch": generate
    if [ -t 1 ]; then nh os {{ action }}; else nh os {{ action }} --no-nom; fi

# activate the configuration now
@switch: (os "switch")

# activate the configuration at the next boot
@boot: (os "boot")

# activate the configuration without making it the boot default
@test: (os "test")

# format the tree with treefmt, e.g. `just fmt --ci`
@fmt *flags: add
    nix fmt -- {{ flags }}

# run the update script of each package that has one
@update-packages *packages: generate
    nix run .#update-packages -- {{ packages }}

# update the flake inputs, then update each package
update: generate
    nix flake update
    just update-packages
