{
  flake.aspects =
    { aspects, ... }:
    {
      gui.includes = with aspects; [
        core

        # keep-sorted start
        _1password
        agent-browser
        agents
        audio
        bat
        bb
        btop
        clipboard
        comma
        crush
        cursor
        direnv
        eza
        face
        fd
        fonts
        fx
        fzf
        gh
        git
        gnome-keyring
        greeter
        hardware
        helium
        herdr
        hyprland
        kitty
        lazygit
        lock
        logind
        mcp
        minecraft
        mosh
        nautilus
        nixcord
        nixvim
        noctalia
        omp
        opencode2
        ozone
        pi-coding-agent
        prime-agent
        ripgrep
        spicetify
        spotify-player
        steam
        stylix
        tmux
        udisks
        upower
        vacuum-tube
        wakatime
        wallpaper
        xdg-autostart
        yazi
        yt-dlp
        zed-editor
        zoxide
        # keep-sorted end
      ];
    };
}
