{
  flake.aspects =
    { aspects, ... }:
    {
      gui.includes = with aspects; [
        core

        # keep-sorted start
        _1password
        agent-browser
        agents
        audio
        bat
        btop
        clipboard
        codex
        comma
        crush
        cursor
        delta-db
        difftastic
        direnv
        eza
        face
        fastpotify
        fd
        fonts
        fx
        fzf
        gh
        git
        gnome-keyring
        greeter
        hardware
        helium
        helix
        herdr
        hyprland
        jq
        kitty
        lazygit
        lock
        logind
        mcp
        minecraft
        mosh
        nautilus
        nixcord
        noctalia
        omp
        opencode2
        ozone
        pi-coding-agent
        prime-agent
        python
        ripgrep
        searxng
        steam
        stylix
        tmux
        udisks
        upower
        vacuum-tube
        wakatime
        wallpaper
        xdg-autostart
        yazi
        yt-dlp
        zed-editor
        zoxide
        # keep-sorted end
      ];
    };
}
